spring:
  application:
    name: demo-flyway

  datasource:
    url: jdbc:mysql://localhost:3306/localdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true