CREATE TABLE tb_otp (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    otp VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    is_used BOOLEAN DEFAULT FALSE,
    expiry_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);